title: "Rockit 2025 Harvest"

subtitle: "Weekly Commentary"
  
date: 04/20/2025
date-format: long

mainfont: Geograph
monofont: Geograph
sansfont: Geograph

prefer-html: true
always_allow_html: yes
  


